[package]
name = "alamgu-async-block"
version = "0.1.2"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = { workspace = true }
pin-project = { workspace = true }
ledger_device_sdk = { workspace = true }
ledger-parser-combinators = { path = "../ledger-parser-combinators" }

[features]
default = []
