name: Swap functional tests

on:
  workflow_dispatch:
  push:
      branches:
        - master
        - main
        - develop
  pull_request:
  
jobs:
    job_functional_tests:
      #uses: LedgerHQ/app-exchange/.github/workflows/reusable_swap_functional_tests.yml@develop
      uses: hoodieshq/app-exchange/.github/workflows/reusable_swap_functional_tests.yml@bn-sui-swap-support
      with:
        branch_for_exchange: 'bn-sui-swap-support' # REMOVE 
        branch_for_sui: ${{ github.ref }}
        test_filter: '"SUI or sui or Sui"'