name: Swap functional tests

on:
  workflow_dispatch:
  push:
      branches:
        - master
        - main
        - develop
  pull_request:
  
jobs:
    job_functional_tests:
      uses: LedgerHQ/app-exchange/.github/workflows/reusable_swap_functional_tests.yml@develop
      with:
        branch_for_exchange: 'bn-add-sui-swap-token-tests'
        repo_for_exchange: 'hoodieshq/app-exchange'
        repo_for_sui: 'hoodieshq/app-sui'
        branch_for_sui: 'bn-add-swap-token-support'
        test_filter: '"SUI or sui or Sui"'